Added Leads tests
NatalliaTsvirko/Salesforce_Diploma_Project pull request #1
Opened 2022-02-11 18:05 UTC by NatalyaTsvirko1

2022-02-13 19:46 UTC, voropa requested changes

2022-02-13 19:46 UTC, voropa commented on README.md
> +-selenium version 4.1.1;
Вроде селениум версии 3 используем

2022-02-13 19:46 UTC, voropa commented on README.md
> +-selenium version 4.1.1;
Перепроверь остальные версии тоже

2022-02-13 19:46 UTC, voropa commented on src/test/java/modals/AccountModal.java
> +        log.info(String.format("Filling form with account info: $s",account));
%

2022-02-13 19:46 UTC, voropa commented on src/test/java/modals/AccountModal.java
> +        WebElement searchFieldToClick = driver.findElement(By.xpath(String.format(listLocator)));
Зачем тут String.format(), если listLocator - не шаблонная строка и туда ничего не  подставляется

2022-02-13 19:46 UTC, voropa commented on src/test/java/modals/AccountModal.java
> +    public void selectOption(String optionName) {
А какую опцию и где этот метод выбирает? из названия не понятно

2022-02-13 19:46 UTC, voropa commented on src/test/java/modals/ContactsModal.java
> +    public void selectOption(String optionName) {
То же самое тут. Не понятно какую опцию и откуда выбирает

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/AccountDetailsPage.java
> +    @Override
Если используешь loadable component паттерн, то нужно тогда везде для каждой страницы нормально переопределять методы open , isPageOpened, а не делать их return null/false

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/AccountDetailsPage.java
> +        log.info(String.format("Filling form with account info: $s", account));
%

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/AccountsPage.java
> +    public boolean getNotificationMessage() {
Опять же таки название метода должн осоответсвовать тому, что он  делает.
Этот метод не получает текст с notification message, а проверяет, отображается ли он. Значит название должно быть is....Displayed()

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/BasePage.java
> +    protected static final Logger log = LogManager.getLogger(BasePage.class.getName());
В других классах  ты инициализируешь логер через lombok аннотацию, а тут вручную. Выбери один подход и сделай везеде единооьразно

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/HomePage.java
> +        return true;
Зачем этот метод всегда возвращет true???

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/LeadsDetailsPage.java
> +        return createdLeadsMessage;
Зачем этот метод возвращает Webelement? он  потом где-то используется?

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/LeadsPage.java
> +    final By SUCCESS_MESSAGE = By.xpath("//div[@class='forceVisualMessageQueue']//*[contains(@class,'slds-theme--succes')]");
Я нашел такой локатор и метод getNotificationMessage минимум в 3х page-классах. Значит этот метод и локатор можно вынести в BasePage, чтобы не дублировать код, так как явно этот самый notification message и его поведение одинаковое на всех страницах salesforce приложения

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/LeadsPage.java
> +        WebElement optionToClick = driver.findElement(By.xpath(String.format(optionLocator)));
Разве тут нужен String.format()? И разве эоемент, который ты ищешь - это option? Судя по  локатору - это delete button. так что название должно быть соответсвующее

2022-02-13 19:46 UTC, voropa commented on src/test/java/pages/LeadsPage.java
> +    public int getVisibleLeadsByCountName(String name){
дословный перевод метода: "получить видимых лидов по колличеству имен". Это я к тому, что название метода нужно переделать)

2022-02-13 19:46 UTC, voropa commented on src/test/java/tests/CreateAccountTest.java
> +        homePage = new HomePage(driver);
HomePage уже  и так инициализщируется в setUp() методе BaseTest'a, зачем ее инициализировать еще раз

2022-02-13 19:46 UTC, voropa commented on src/test/java/tests/CreateAccountTest.java
> +        log.info("opening account page");
В тестах не должно быть логов!
Логи - это техническая информация, поэтому она должна быть спрятана как минимум на уровень page-классов

2022-02-13 19:46 UTC, voropa commented on src/test/java/tests/CreateAccountTest.java
> +        AllureUtils.attachScreenshot(driver);
Точно так же и AllureUtils.attachScreenshot() - техническая штука, которой не должно быть в тестах, перенести в page-классы

2022-02-13 19:46 UTC, voropa commented on src/test/java/tests/CreateAccountTest.java
> +        accountsPage.getNotificationMessage();
Какоой смысл от этого действия в тесте. 
получили мы notificationMessage. никуда его не записали ни в какую переменную, не проверили с помощью assert'a... так зачем он тут

2022-02-13 19:46 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +    public void createLeadsPage() {
Очень странное название для тестового метода

2022-02-13 19:46 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +        assertEquals(actualMessage, expectedMessage);
А почему тест не  проверяет, что lead действительно сохранился, как тесты на аккаунт и контакт?

2022-02-13 19:46 UTC, voropa commented on src/test/resources/config.properties
> +chromedriver =src/main/resources/chromedriver.exe
А он нам нужен? мы же  вроде используем webddrivermanager библиотеку, которая за нас скачивает нужный драйвер

2022-02-13 19:48 UTC, voropa commented
Честно говоря не тянет на дипломную работую У тебя всего 3 теста, исключая тесты на login/logout. Да и тест на создание lead'a еще не доделан, он не проверяет, что обьект lead с такими атрибутами действително создался...

2022-02-14 20:32 UTC, NatalliaTsvirko commented on README.md
> +-selenium version 4.1.1;
Перепроверила и заменила версии

2022-02-14 20:32 UTC, NatalliaTsvirko commented on src/test/java/modals/AccountModal.java
> +        log.info(String.format("Filling form with account info: $s",account));
исправила на %

2022-02-14 20:34 UTC, NatalliaTsvirko commented on src/test/java/modals/AccountModal.java
> +        WebElement searchFieldToClick = driver.findElement(By.xpath(String.format(listLocator)));
исправила

2022-02-14 20:34 UTC, NatalliaTsvirko commented on src/test/java/modals/AccountModal.java
> +    public void selectOption(String optionName) {
исправила название метода

2022-02-14 20:35 UTC, NatalliaTsvirko commented on src/test/java/modals/ContactsModal.java
> +    public void selectOption(String optionName) {
исправила название метода

2022-02-14 20:37 UTC, NatalliaTsvirko commented on src/test/java/pages/AccountDetailsPage.java
> +    @Override
все исправила и добавила ссылки

2022-02-14 20:38 UTC, NatalliaTsvirko commented on src/test/java/pages/AccountDetailsPage.java
> +        log.info(String.format("Filling form with account info: $s", account));
исправила

2022-02-14 20:39 UTC, NatalliaTsvirko commented on src/test/java/pages/AccountsPage.java
> +    public boolean getNotificationMessage() {
исправила и вынесла в BasePage.

2022-02-14 20:39 UTC, NatalliaTsvirko commented on src/test/java/pages/BasePage.java
> +    protected static final Logger log = LogManager.getLogger(BasePage.class.getName());
проинициализировала через lombok

2022-02-14 20:40 UTC, NatalliaTsvirko commented on src/test/java/pages/HomePage.java
> +        return true;
сделала методом void

2022-02-14 20:41 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsDetailsPage.java
> +        return createdLeadsMessage;
исправила и вынесла в BasePage

2022-02-14 20:42 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsPage.java
> +    final By SUCCESS_MESSAGE = By.xpath("//div[@class='forceVisualMessageQueue']//*[contains(@class,'slds-theme--succes')]");
вынесла метод в BasePage

2022-02-14 20:43 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsPage.java
> +        WebElement optionToClick = driver.findElement(By.xpath(String.format(optionLocator)));
исправила

2022-02-14 20:43 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsPage.java
> +    public int getVisibleLeadsByCountName(String name){
А название этого метода подсказал мне ты ))

2022-02-14 20:45 UTC, NatalliaTsvirko commented on src/test/java/tests/CreateAccountTest.java
> +        homePage = new HomePage(driver);
исправила

2022-02-14 20:45 UTC, NatalliaTsvirko commented on src/test/java/tests/CreateAccountTest.java
> +        log.info("opening account page");
удалила

2022-02-14 20:45 UTC, NatalliaTsvirko commented on src/test/java/tests/CreateAccountTest.java
> +        AllureUtils.attachScreenshot(driver);
удалила

2022-02-14 20:54 UTC, NatalliaTsvirko commented on src/test/java/tests/CreateAccountTest.java
> +        accountsPage.getNotificationMessage();
добавила assert

2022-02-14 20:55 UTC, NatalliaTsvirko commented on src/test/java/tests/LeadsTest.java
> +    public void createLeadsPage() {
) исправила

2022-02-14 20:55 UTC, NatalliaTsvirko commented on src/test/resources/config.properties
> +chromedriver =src/main/resources/chromedriver.exe
удалила

2022-02-14 20:57 UTC, NatalliaTsvirko commented on src/test/java/tests/LeadsTest.java
> +        assertEquals(actualMessage, expectedMessage);
потому что там нет details page. Только сообщение о том ,что сконвертировался lead. А затем просто открывает список лидов. А какой лид создался я не знаю т.к. использую faker

2022-02-18 16:38 UTC, voropa commented
Удали chromedriver.exe из resources папки. так как он не  нужен

2022-02-18 16:41 UTC, voropa commented
Почему картинки лежат в src/**main**/resources? 
У нас же проект с автотестами. так что все должно быть в src/**test** и java код  и ресурсы. 
в scr/main лежал бы основной код приложения, которое мы тестируем, если бы оно у нас было

2022-02-18 17:39 UTC, voropa requested changes

2022-02-18 17:39 UTC, voropa commented on src/test/java/modals/GroupsModal.java
> +        File file = new File("src/main/resources/spongebob.jpg");
Почему путь к файлу захардкодан тут. Как минимум он должен передаваться входным аргументом в методе chooseFile() т.к. файл - это тестовые данные

2022-02-18 17:39 UTC, voropa commented on src/test/java/modals/GroupsModal.java
> +        //driver.findElement(NEXT_BUTTON).click();
Удали либо раскоментируй эту строчку

2022-02-18 17:39 UTC, voropa commented on src/test/java/modals/LeadsModal.java
> +        log.info(String.format("Filling form with account info: %s", lead));
Перепроверь сообщения в логах во всех fillForm методах. У тебя везде в тексте 'Filling form with **account** info", а на самом деле не аккаунт инфо заполняется

2022-02-18 17:39 UTC, voropa commented on src/test/java/modals/LeadsModal.java
> +    public String createLeadText() {
Уже говорили про названия методов. Метод, котторый получает какой-то текст должен содержать в имени слово "get"

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/AccountDetailsPage.java
> +        driver.get(BASE_URL + "lightning/r/Account/0015j00000XaFT1AAN/view");
Не думаю, что такой URL всегда сработает, так как в нем явно какой-то id конкретного аккаунта. 
В таких случаях, когда для страницы нельзя определить константный URL и страница динамическая, то метод open() нужно не переопределять, так как использовать его не получится

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/ContactDetailsPage.java
> +        driver.get(BASE_URL + "/lightning/r/Contact/0035j00000JJaW4AAL/view");
То же самое тут с URL

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/ContactsPage.java
> +        driver.switchTo().frame(0);
А зачем 2 раза подряд делать switchTo.frame ?

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/GroupDetailsPage.java
> +        driver.get(BASE_URL + "/lightning/r/CollaborationGroup/0F95j000000kJiOCAU/view");
URL

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/LeadsDetailsPage.java
> +        driver.get(BASE_URL + "/lightning/r/Lead/00Q5j000006bQoFEAU/view");
URL

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/LeadsDetailsPage.java
> +    public boolean getMessageConvertLead() {
если  метод проверяет, что message.isDisplayed(), то он должен называтся isConvertLeadMessageDisplayed()

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/LeadsPage.java
> +    public int getVisibleLeadName(String name) {
странное название метода. Не соответсвует тому, что он делает

2022-02-18 17:39 UTC, voropa commented on src/test/java/pages/LeadsPage.java
> +    @Step("Open delete option on leads from list")
Тут у тебя 2 метода с похожим названием и функционалом. Я так и не  понял, какой из них удаляет лида...
Либо обьедини их в один метод, либо переименуй таким образом, чтобы название отображало действие, которое он выполняет

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/CalendarTest.java
> +        String expectedEventDate = "2/21/2022, 12:00 AM";
А если этот тест запустить в марте, то он не пройдет))
Так что в методе, где ты утсанавливаешь дату, лучше утсанавливать полную дату, а не только день и проверять потом полную дату

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/CreateAccountTest.java
> +        accountsPage.setAccountName("Chin");
"Chin" - имя аккаунта можно вынести в константу в начале теста и переиспользовать в этих двух строчках.
а вообще не факт, что будет такой аккаунт с именем "Chin" каждый раз когда ты запускаешь тест. 
так что лучше либо перед тестом создавать аккаунт, либо переделать логику теста, чтобы он выбирал первый попавшийся из списка и делал  поиск по нему

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/DriverFactory.java
> +            //options.addArguments("--headless");
Почему закоментировано?
Лучше вынести этот параметр в какой-нибуль pom.xml или suite.xml, как сделано с browserName

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +        leadsPage.clickOpportunityMenuLink();
Тут ты на строчке 72 перешла на opportunities вкладку, соответсвенно у тебя уже  другая страница, а ты вызываешь методы со страницы leadsPage, так  быть не доолжно

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +        String findByName = leadName.getCompany();
А тут обратная ситуация с именем переменной. Имя переменной должно быть существительным, а у тебя это глагол)

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +        int numberOfElements = leadsPage.getVisibleLeadName(findByName);
Слишком абстрактное название переменной numberOfElements. Сделай его более информативным

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +        int numberOfElements = leadsPage.getVisibleLeadName(findByName);
В тестах ниже то же самое с этими переменными

2022-02-18 17:39 UTC, voropa commented on src/test/java/tests/LeadsTest.java
> +        int numberOfElements = leadsPage.getVisibleLeadName(findByName);
И вообще этот ассерт можно  написать в одну строчку вместо трех:
assertEquals(opportunitiesPage.getVisibleitemsByName(eadName.getCompany()), 1, "Element not found");

2022-02-18 17:40 UTC, voropa commented
И отформатируй весь код, у тебя много лишних пробелов и отступов. 
IDEA это сама может сделать за тебя, если нажать ПКМ на проект
<img width="495" alt="image" src="https://user-images.githubusercontent.com/14195681/154734312-b327d005-50c2-4b9b-a3d3-18a2f94c069a.png">

2022-02-18 17:48 UTC, NatalliaTsvirko commented on src/test/java/modals/GroupsModal.java
> +        //driver.findElement(NEXT_BUTTON).click();
удалила

2022-02-18 17:48 UTC, NatalliaTsvirko commented on src/test/java/modals/LeadsModal.java
> +        log.info(String.format("Filling form with account info: %s", lead));
исправила

2022-02-18 17:51 UTC, NatalliaTsvirko commented on src/test/java/pages/AccountDetailsPage.java
> +        driver.get(BASE_URL + "lightning/r/Account/0015j00000XaFT1AAN/view");
исправила

2022-02-18 17:53 UTC, NatalliaTsvirko commented on src/test/java/modals/LeadsModal.java
> +    public String createLeadText() {
забыла удалить, я его нигде не использую. Удалила

2022-02-18 17:54 UTC, NatalliaTsvirko commented on src/test/java/pages/ContactDetailsPage.java
> +        driver.get(BASE_URL + "/lightning/r/Contact/0035j00000JJaW4AAL/view");
исправила

2022-02-18 17:55 UTC, NatalliaTsvirko commented on src/test/java/pages/ContactsPage.java
> +        driver.switchTo().frame(0);
Там iframe в iframe

2022-02-18 17:55 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsDetailsPage.java
> +        driver.get(BASE_URL + "/lightning/r/Lead/00Q5j000006bQoFEAU/view");
исправила

2022-02-18 17:57 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsDetailsPage.java
> +    public boolean getMessageConvertLead() {
исправила

2022-02-18 18:00 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsPage.java
> +    public int getVisibleLeadName(String name) {
переименовала "getLeadNameOnList"

2022-02-18 18:02 UTC, NatalliaTsvirko commented on src/test/java/pages/LeadsPage.java
> +    @Step("Open delete option on leads from list")
объединила

2022-02-18 18:05 UTC, NatalliaTsvirko commented on src/test/java/tests/CalendarTest.java
> +        String expectedEventDate = "2/21/2022, 12:00 AM";
)) Тут проблема, в ручную не дает вписать дату. И поэтому это очень плохой тест, который берет дату из календаря на Calendar Page, а затем только открывает форму для заполнения и там уже отображается выбранная ранее дата... Я уже и не знаю как еще там можно сделать..

2022-02-18 18:12 UTC, NatalliaTsvirko commented on src/test/java/tests/LeadsTest.java
> +        String findByName = leadName.getCompany();
))  моя боль... Исправила "leadNameCompany"

2022-02-18 18:30 UTC, NatalliaTsvirko commented on src/test/java/tests/LeadsTest.java
> +        leadsPage.clickOpportunityMenuLink();
Создала новую страницу, все исправила

2022-02-18 18:30 UTC, NatalliaTsvirko commented on src/test/java/tests/LeadsTest.java
> +        int numberOfElements = leadsPage.getVisibleLeadName(findByName);
А так можно было ?! Все исправила

2022-02-18 18:35 UTC, NatalliaTsvirko commented on src/test/java/modals/GroupsModal.java
> +        File file = new File("src/main/resources/spongebob.jpg");
исправила, надеюсь правильно.

2022-02-18 18:53 UTC, NatalliaTsvirko commented on src/test/java/tests/CreateAccountTest.java
> +        accountsPage.setAccountName("Chin");
Тест переделала, сначала создаю а потом передаю аккаунт в поиск

2022-02-18 18:58 UTC, NatalliaTsvirko commented on src/test/java/tests/DriverFactory.java
> +            //options.addArguments("--headless");
Я его удалила , т.к. я его не использую..

2022-02-19 11:19 UTC, voropa commented on src/test/java/tests/CalendarTest.java
> +        calendarModal.setEventDate("02/26/2022");
Лучше дату и  время вынести в константы,  так как это входные данные для теста и потом expectedDate сформировать из них по типу: 
expectedDate =  testDate + ", " + testTime
чтобы при изменении тестовых данных не приходилось править в нескольких метсах

2022-02-19 11:19 UTC, voropa commented on src/test/java/tests/CalendarTest.java
> +        calendarPage.clickCreatedEventDay(expectedDate, "Meeting");
Почему хардкод? У тебя же есть тип ивента в testCalendar обьекте и его можно оттуда получить через testCalendar.getSubject

2022-02-19 11:19 UTC, voropa commented on src/test/java/modals/CalendarModal.java
> +        actions.moveToElement(driver.findElement(DATE_FIELD_START)).click()
Это все можно обьединить в одну цепочку actions:
actions.moveToElement().click().sendKeys(clear).sendKeys(startDate).build().perform()

2022-02-19 14:12 UTC, NatalliaTsvirko commented on src/test/java/tests/CalendarTest.java
> +        calendarModal.setEventDate("02/26/2022");
исправила

2022-02-19 14:16 UTC, NatalliaTsvirko commented on src/test/java/modals/CalendarModal.java
> +        actions.moveToElement(driver.findElement(DATE_FIELD_START)).click()
заменила на selenium element.clear()

2022-02-19 14:16 UTC, NatalliaTsvirko commented on src/test/java/tests/CalendarTest.java
> +        calendarPage.clickCreatedEventDay(expectedDate, "Meeting");
исправила.

2022-02-19 14:21 UTC, voropa approved these changes

2022-02-19 14:33 UTC, merged